/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import javax.swing.ImageIcon;
import model.Person;

/**
 *
 * @author bhavana
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Person person;
    public ViewJPanel(Person person) {
        initComponents();
        this.person=person;
        
        displayPerson();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblGeographicdata = new javax.swing.JLabel();
        lbldob = new javax.swing.JLabel();
        lblTelephoneNumber = new javax.swing.JLabel();
        lblFAX = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblMedicalRecordNumber = new javax.swing.JLabel();
        lblHealthPlanBenificiaryNumber = new javax.swing.JLabel();
        lblBankAccountNumber = new javax.swing.JLabel();
        lblLicenseNumber = new javax.swing.JLabel();
        lblVehicleIdentifiers = new javax.swing.JLabel();
        lblDeviceIdentifiers = new javax.swing.JLabel();
        lblLinkedIn = new javax.swing.JLabel();
        lblInternetProtocolAddresses = new javax.swing.JLabel();
        lblBiometricIdentifiers = new javax.swing.JLabel();
        lblFullFacePhotos = new javax.swing.JLabel();
        lblUniqueIdentifyingNumber = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGeographicdata = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        txtTelephoneNumber = new javax.swing.JTextField();
        txtFAX = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtMedicalRecordNumber = new javax.swing.JTextField();
        txtHealthPlanBenificiaryNumber = new javax.swing.JTextField();
        txtBankAccountNumber = new javax.swing.JTextField();
        txtLicenseNumber = new javax.swing.JTextField();
        txtVehicleIdentifiers = new javax.swing.JTextField();
        txtDeviceIdentifiers = new javax.swing.JTextField();
        txtLinkedIn = new javax.swing.JTextField();
        txtInternetProtocolAddresses = new javax.swing.JTextField();
        txtBiometricIdentifiers = new javax.swing.JTextField();
        txtFullFacePhotos = new javax.swing.JTextField();
        txtUniqueIdentifyingNumber = new javax.swing.JTextField();
        lblImgFullFacePhotos = new javax.swing.JLabel();
        lblImgBiometricIdentifiers = new javax.swing.JLabel();

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("VIEW");

        lblName.setText("Name");

        lblGeographicdata.setText("Geographic Data");

        lbldob.setText("Date of Birth");

        lblTelephoneNumber.setText("Telephone Number");

        lblFAX.setText("FAX Number");

        lblEmail.setText("Email Address");

        lblSSN.setText("Social Security Number");

        lblMedicalRecordNumber.setText("Medical Record Number");

        lblHealthPlanBenificiaryNumber.setText("Health plan beneficiary number");

        lblBankAccountNumber.setText("Bank account number");

        lblLicenseNumber.setText("License number");

        lblVehicleIdentifiers.setText("Vehicle identifiers");

        lblDeviceIdentifiers.setText("Device identifiers");

        lblLinkedIn.setText("LinkedIn");

        lblInternetProtocolAddresses.setText("Internet protocol addresses");

        lblBiometricIdentifiers.setText("Biometric identifiers");

        lblFullFacePhotos.setText("Full face photos ");

        lblUniqueIdentifyingNumber.setText("Unique identifying number");

        txtGeographicdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeographicdataActionPerformed(evt);
            }
        });

        txtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUniqueIdentifyingNumber)
                    .addComponent(lblFullFacePhotos)
                    .addComponent(lblBiometricIdentifiers)
                    .addComponent(lblInternetProtocolAddresses)
                    .addComponent(lblLinkedIn)
                    .addComponent(lblDeviceIdentifiers)
                    .addComponent(lblVehicleIdentifiers)
                    .addComponent(lblLicenseNumber)
                    .addComponent(lblBankAccountNumber)
                    .addComponent(lblHealthPlanBenificiaryNumber)
                    .addComponent(lblEmail)
                    .addComponent(lblFAX)
                    .addComponent(lblTelephoneNumber)
                    .addComponent(lbldob)
                    .addComponent(lblGeographicdata)
                    .addComponent(lblName)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblSSN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMedicalRecordNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtFullFacePhotos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(txtBiometricIdentifiers, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtInternetProtocolAddresses, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtLinkedIn, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtDeviceIdentifiers, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtVehicleIdentifiers, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtLicenseNumber, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtBankAccountNumber, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtHealthPlanBenificiaryNumber, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtSSN, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFAX, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(txtTelephoneNumber)
                        .addComponent(txtDob)
                        .addComponent(txtGeographicdata)
                        .addComponent(txtName))
                    .addComponent(txtUniqueIdentifyingNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImgFullFacePhotos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImgBiometricIdentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeographicdata)
                    .addComponent(txtGeographicdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldob)
                            .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelephoneNumber)
                            .addComponent(txtTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFAX)
                            .addComponent(txtFAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSSN)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMedicalRecordNumber)
                            .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHealthPlanBenificiaryNumber)
                            .addComponent(txtHealthPlanBenificiaryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblImgBiometricIdentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankAccountNumber)
                    .addComponent(txtBankAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLicenseNumber)
                            .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVehicleIdentifiers)
                            .addComponent(txtVehicleIdentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDeviceIdentifiers)
                            .addComponent(txtDeviceIdentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLinkedIn)
                            .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInternetProtocolAddresses)
                            .addComponent(txtInternetProtocolAddresses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBiometricIdentifiers)
                            .addComponent(txtBiometricIdentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFullFacePhotos)
                            .addComponent(txtFullFacePhotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblImgFullFacePhotos, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUniqueIdentifyingNumber)
                    .addComponent(txtUniqueIdentifyingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtGeographicdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeographicdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeographicdataActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBankAccountNumber;
    private javax.swing.JLabel lblBiometricIdentifiers;
    private javax.swing.JLabel lblDeviceIdentifiers;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFAX;
    private javax.swing.JLabel lblFullFacePhotos;
    private javax.swing.JLabel lblGeographicdata;
    private javax.swing.JLabel lblHealthPlanBenificiaryNumber;
    private javax.swing.JLabel lblImgBiometricIdentifiers;
    private javax.swing.JLabel lblImgFullFacePhotos;
    private javax.swing.JLabel lblInternetProtocolAddresses;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedicalRecordNumber;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTelephoneNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUniqueIdentifyingNumber;
    private javax.swing.JLabel lblVehicleIdentifiers;
    private javax.swing.JLabel lbldob;
    private javax.swing.JTextField txtBankAccountNumber;
    private javax.swing.JTextField txtBiometricIdentifiers;
    private javax.swing.JTextField txtDeviceIdentifiers;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFAX;
    private javax.swing.JTextField txtFullFacePhotos;
    private javax.swing.JTextField txtGeographicdata;
    private javax.swing.JTextField txtHealthPlanBenificiaryNumber;
    private javax.swing.JTextField txtInternetProtocolAddresses;
    private javax.swing.JTextField txtLicenseNumber;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedicalRecordNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtTelephoneNumber;
    private javax.swing.JTextField txtUniqueIdentifyingNumber;
    private javax.swing.JTextField txtVehicleIdentifiers;
    // End of variables declaration//GEN-END:variables

    private void displayPerson() {
        txtName.setText(person.getName());
        txtGeographicdata.setText(person.getGeographicData());
        txtDob.setText(person.getDob());
        txtTelephoneNumber.setText(person.getTelephoneNumber());
        txtFAX.setText(person.getFaxNumber());
        txtEmail.setText(person.getEmailAddress());
        txtSSN.setText(person.getSsn());
        txtMedicalRecordNumber.setText(person.getMedicalRecordNumber());
        txtHealthPlanBenificiaryNumber.setText(person.getHealthPlanBenificiaryNumber());
        txtBankAccountNumber.setText(person.getBankAccountNumber());
        txtLicenseNumber.setText(person.getLicenseNumber());
        txtVehicleIdentifiers.setText(person.getVehicleIdentifiers());
        txtDeviceIdentifiers.setText(person.getDeviceIdentifiers());
        txtLinkedIn.setText(person.getLinkedIn());
        txtInternetProtocolAddresses.setText(person.getInternetProtocolAddresses());
        txtBiometricIdentifiers.setText(person.getBiometricIdentifiers());
        txtFullFacePhotos.setText(person.getFullFacePhotos());
        txtUniqueIdentifyingNumber.setText(person.getUniqueIdentifyingNumber());
        
        String filename = person.getBiometricIdentifiers();
        txtBiometricIdentifiers.setText(filename);
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(138, 152, Image.SCALE_DEFAULT));
        lblImgBiometricIdentifiers.setIcon(imageIcon);
        
        String filename1 = person.getFullFacePhotos();
        txtFullFacePhotos.setText(filename1);
        ImageIcon imageIcon1 = new ImageIcon(new ImageIcon(filename1).getImage().getScaledInstance(138, 152, Image.SCALE_DEFAULT));
        lblImgFullFacePhotos.setIcon(imageIcon1);
        
        
    }
}
